### ISSUE TITLE
Can't display anything at goban again

### ISSUE THREAD

**Issue by jun63cn** [kaorahi/lizgoban#29] opened 2019-06-29 14:03 UTC
![无标题](https://user-images.githubusercontent.com/30382868/60385241-bc486880-9ab9-11e9-9ca2-16e4cc3fd6e5.jpg)

**Comment by kaorahi** [comment] 2019-06-29 14:32
Thx for the report.

1. Are there any errors in [Debug] ==> [Toggle Developer Tools] ==> Console ?
2. Would you try 'binary search' to find which commit caused the problem?

**Comment by jun63cn** [comment] 2019-06-29 15:10
1、nothing
2、Commits on Jun 10, 2019  works well. after Jun 16  All  commits do not work.

**Comment by kaorahi** [comment] 2019-06-29 15:47
Would you tell me exactly "which commit" caused the problem? This is important for debugging. Did you say that bf65709d is OK and a333a96a is NG? How about commits between them?

**Comment by jun63cn** [comment] 2019-06-29 23:29
a333a96~90d3731 are NG

**Comment by kaorahi** [comment] 2019-06-30 00:33
thx. I reverted 6aa6b4e0. Does d536ca40 work?

In addition, would you try the old commits from 5a1a81c9 to 77c6bf6b to specify the cause of the previous issue #4? It will help my understanding of your problem and may prevent future bugs. I've heard that 6909bdbd was NG and fe9e52ad was OK.

**Comment by jun63cn** [comment] 2019-06-30 12:41
d536ca4 does not work.

> 
I've heard that [6909bdb](https://github.com/kaorahi/lizgoban/commit/6909bdbdee2c9563b7f6ede6f531ebf19a185602) was NG and [fe9e52a](https://github.com/kaorahi/lizgoban/commit/fe9e52ad786e689b08ef35c3d8049f846d8f3ada) was OK.

It's confirmed.
5a1a81c was NG  It's crash when set debug trace. because no way to stop leelaz running. So as 8797087 .
aa1a487 and 77c6bf6 works well here.

**Comment by kaorahi** [comment] 2019-06-30 14:39
Then would you try this?

1. Download 7578133d.
2. `npx electron src -c debug1.json` with the following `debug1.json`.
~~~
{"engine_log_line_length": 100, "analyze_interval_centisec": 100}
~~~

I'd like to know what is shown on the console (from the beginning).

My case:
~~~
$ npx electron src -c debug1.json
option: {"leelaz_command":"/home/foo/lizgoban/external/leelaz","leelaz_args":["-g","-w","/home/foo/lizgoban/external/network.gz"],"analyze_interval_centisec":100,"minimum_suggested_moves":30,"engine_log_line_length":100,"sabaki_command":"/home/foo/lizgoban/external/sabaki","minimum_auto_restart_millisec":5000,"wait_for_startup":true,"endstate_leelaz":null,"shortcut":null}
5209.35 [undefined] start leela zero: ["/home/foo{...41...}","/home/foo/lizgoban/external/network.gz"]
5209.36 [17211] queue> clear_board []
5209.36 [17211] queue> lz-analyze 100 [clear_board]
5209.42 [17211] stderr| Using 8 thread(s).
5209.42 [17211] stderr| RNG seed: 11638767112249136448
5209.42 [17211] stderr| BLAS Core: built-in Eigen 3.3.7 library.
5209.58 [17211] queue> lz-analyze 100 [clear_board,lz-analyze 100]
5209.83 [17211] stderr| Detecting residual layers...v1...192 channels...15 blocks.
5210.23 [17211] stderr| Initializing CPU-only evaluation.
5210.23 [17211] stderr| Setting max tree size to 4324 MiB and cache size to 480 MiB.
5210.23 [17211] leelaz>  0 komi 7.5 [clear_board,lz-analyze 100]
5210.23 [17211] leelaz>  1 lz-analyze interval 1 minmoves 30 [clear_board,lz-analyze 100]
5210.23 [17211] leelaz>  2 name [clear_board,lz-analyze 100]
5210.23 [17211] leelaz>  3 endstate_map [clear_board,lz-analyze 100]
5210.23 [17211] leelaz>  4 name [clear_board,lz-analyze 100]
5210.23 [17211] leelaz>  5 kata-analyze interval 1 [clear_board,lz-analyze 100]
5210.23 [17211] leelaz>  6 name [clear_board,lz-analyze 100]
5210.23 [17211] leelaz>  7 name [clear_board,lz-analyze 100]
5210.23 [17211] stdout| =0 
5210.23 [17211] stdout| 
5210.23 [17211] stdout| =1
5210.23 [17211] queue> lz-analyze interval 100 minmoves 30 [clear_board,lz-analyze 100]
5210.29 [17211] stderr| NN eval=0.427636
5210.45 [17211] stdout| info move Q16 visits 1 win{...1816...}7 visits 0 winrate 0 prior 7 lcb 0 order 29 pv P17
5210.58 [17211] stderr| 
5210.59 [17211] stderr|  Q16 ->       3 (V: 42.88%) (LCB:  0.00%) (N: 15.47%) PV: Q16 D16
5210.59 [17211] stderr|  C16 ->       2 (V: 43.80%) (LCB:  0.00%) (N:  4.23%) PV: C16 C3
5210.59 [17211] stderr|   D4 ->       2 (V: 43.17%) (LCB:  0.00%) (N: 15.40%) PV: D4 Q16
5210.59 [17211] stderr|   Q4 ->       2 (V: 43.08%) (LCB:  0.00%) (N: 15.28%) PV: Q4 D16
5210.59 [17211] stderr|  D16 ->       2 (V: 42.98%) (LCB:  0.00%) (N: 15.23%) PV: D16 Q4
5210.59 [17211] stderr|  D17 ->       2 (V: 42.94%) (LCB:  0.00%) (N:  4.17%) PV: D17 R17
5210.59 [17211] stderr|   C4 ->       1 (V: 43.12%) (LCB:  0.00%) (N:  4.10%) PV: C4 
5210.59 [17211] stderr|   D3 ->       1 (V: 42.81%) (LCB:  0.00%) (N:  4.08%) PV: D3 
5210.59 [17211] stderr| 2.4 average depth, 3 max depth
5210.59 [17211] stderr| 7 non leaf nodes, 2.14 average children
5210.59 [17211] stderr| 
5210.59 [17211] stderr| 16 visits, 5754 nodes
5210.59 [17211] stderr| 
5210.59 [17211] stdout| 
5210.59 [17211] stdout| =2 Leela Zero
5210.59 [17211] stdout| 
5210.59 [17211] stdout| ?3 unknown command
5210.59 [17211] queue> lz-analyze interval 100 min{...8...} [clear_board,lz-analyze interval 100 minmoves 30]
5210.59 [17211] stdout| 
5210.59 [17211] stdout| =4 Leela Zero
5210.59 [17211] stdout| 
5210.59 [17211] stdout| ?5 unknown command
5210.59 [17211] queue> lz-analyze interval 100 min{...8...} [clear_board,lz-analyze interval 100 minmoves 30]
5210.59 [17211] stdout| 
5210.59 [17211] stdout| =6 Leela Zero
5210.59 [17211] stdout| 
5210.59 [17211] stdout| =7 Leela Zero
5210.59 [17211] leelaz>  8 clear_board [lz-analyze interval 100 minmoves 30]
5210.59 [17211] stdout| 
5210.59 [17211] stdout| =8 
5210.59 [17211] leelaz>  9 lz-analyze interval 100 minmoves 30 []
5210.59 [17211] stdout| 
5210.59 [17211] stdout| =9
5210.59 [17211] stderr| NN eval=0.427636
5211.66 [17211] stdout| info move D4 visits 15 win{...2029...}7 visits 0 winrate 0 prior 7 lcb 0 order 29 pv P17
5212.75 [17211] stdout| info move D4 visits 56 win{...2154...}7 visits 0 winrate 0 prior 7 lcb 0 order 29 pv P17
~~~

**Comment by jun63cn** [comment] 2019-06-30 16:08
F:\lizgoban> npx electron src -c debug1.json
option: {"leelaz_command":"F:\\lizgoban\\external\\leelaz","leelaz_args":["-g",
-w","F:\\lizgoban\\external\\network.gz"],"analyze_interval_centisec":100,"mini
um_suggested_moves":30,"engine_log_line_length":100,"sabaki_command":"F:\\lizgo
an\\external\\sabaki","minimum_auto_restart_millisec":5000,"wait_for_startup":t
ue,"endstate_leelaz":null,"shortcut":null}
625.20 [undefined] start leela zero: ["F:\\lizgob{...19...}z","-g","-w","F:\\li
goban\\external\\network.gz"]
625.21 [85568] queue> clear_board []
625.21 [85568] queue> lz-analyze 100 [clear_board]
625.42 [85568] stderr| Using OpenCL batch size of 5
625.42 [85568] stderr| Using 10 thread(s).
625.42 [85568] stderr| RNG seed: 6713643478635714689
625.42 [85568] stderr| BLAS Core: built-in Eigen 3.3.7 library.
625.58 [85568] queue> lz-analyze 100 [clear_board,lz-analyze 100]
629.78 [85568] stderr| Detecting residual layers...v1...256 channels...40 block
.
634.69 [85568] stderr| Initializing OpenCL (autodetecting precision).
634.73 [85568] stderr| Detected 1 OpenCL platforms.
634.73 [85568] stderr| Platform version: OpenCL 1.2 CUDA 10.2.120
634.73 [85568] stderr| Platform profile: FULL_PROFILE
634.73 [85568] stderr| Platform name:    NVIDIA CUDA
634.73 [85568] stderr| Platform vendor:  NVIDIA Corporation
634.73 [85568] stderr| Device ID:     0
634.73 [85568] stderr| Device name:   GeForce GTX 1060 3GB
634.73 [85568] stderr| Device type:   GPU
634.73 [85568] stderr| Device vendor: NVIDIA Corporation
634.73 [85568] stderr| Device driver: 430.64
634.73 [85568] stderr| Device speed:  1759 MHz
634.73 [85568] stderr| Device cores:  9 CU
634.73 [85568] stderr| Device score:  1112
634.73 [85568] stderr| Selected platform: NVIDIA CUDA
634.73 [85568] stderr| Selected device: GeForce GTX 1060 3GB
634.73 [85568] stderr| with OpenCL 1.2 capability.
634.87 [85568] stderr| Half precision compute support: No.
634.90 [85568] stderr| Tensor Core support: No.
634.90 [85568] stderr| Detected 1 OpenCL platforms.
634.90 [85568] stderr| Platform version: OpenCL 1.2 CUDA 10.2.120
634.90 [85568] stderr| Platform profile: FULL_PROFILE
634.90 [85568] stderr| Platform name:    NVIDIA CUDA
634.90 [85568] stderr| Platform vendor:  NVIDIA Corporation
634.90 [85568] stderr| Device ID:     0
634.90 [85568] stderr| Device name:   GeForce GTX 1060 3GB
634.90 [85568] stderr| Device type:   GPU
634.90 [85568] stderr| Device vendor: NVIDIA Corporation
634.91 [85568] stderr| Device driver: 430.64
634.91 [85568] stderr| Device speed:  1759 MHz
634.91 [85568] stderr| Device cores:  9 CU
634.91 [85568] stderr| Device score:  1112
634.91 [85568] stderr| Selected platform: NVIDIA CUDA
634.91 [85568] stderr| Selected device: GeForce GTX 1060 3GB
634.91 [85568] stderr| with OpenCL 1.2 capability.
635.07 [85568] stderr| Half precision compute support: No.
635.09 [85568] stderr| Tensor Core support: No.
635.09 [85568] stderr| Loaded existing SGEMM tuning.
635.10 [85568] stderr| Wavefront/Warp size: 32
635.10 [85568] stderr| Max workgroup size: 1024
635.10 [85568] stderr| Max workgroup dimensions: 1024 1024 64
637.48 [85568] stderr| Loaded existing SGEMM tuning.
637.48 [85568] stderr| Wavefront/Warp size: 32
637.48 [85568] stderr| Max workgroup size: 1024
637.48 [85568] stderr| Max workgroup dimensions: 1024 1024 64
639.63 [85568] stderr| Using OpenCL half precision (at least 5% faster than sin
le).
639.63 [85568] stderr| Setting max tree size to 3736 MiB and cache size to 415
iB.
639.63 [85568] leelaz>  0 komi 7.5 [clear_board,lz-analyze 100]
639.63 [85568] leelaz>  1 lz-analyze interval 1 minmoves 30 [clear_board,lz-ana
yze 100]
639.63 [85568] leelaz>  2 name [clear_board,lz-analyze 100]
639.63 [85568] leelaz>  3 endstate_map [clear_board,lz-analyze 100]
639.63 [85568] leelaz>  4 name [clear_board,lz-analyze 100]
639.63 [85568] leelaz>  5 kata-analyze interval 1 [clear_board,lz-analyze 100]
639.63 [85568] leelaz>  6 name [clear_board,lz-analyze 100]
639.63 [85568] leelaz>  7 name [clear_board,lz-analyze 100]
639.63 [85568] stdout| =0
639.63 [85568] stdout|
639.63 [85568] stdout| =1
639.63 [85568] queue> lz-analyze interval 100 minmoves 30 [clear_board,lz-analy
e 100]
639.63 [85568] stderr| NN eval=0.441899
639.68 [85568] stdout| info move D4 visits 1 winr{...1836...} visits 0 winrate
 prior 10 lcb 0 order 29 pv C15
639.73 [85568] stdout| info move D4 visits 2 winr{...1872...} visits 0 winrate
 prior 10 lcb 0 order 29 pv C15
639.77 [85568] stdout| info move D16 visits 3 win{...1921...} visits 0 winrate
 prior 10 lcb 0 order 29 pv C15
639.82 [85568] stdout| info move D4 visits 5 winr{...1965...} visits 0 winrate
 prior 10 lcb 0 order 29 pv C15
639.87 [85568] stdout| info move D4 visits 7 winr{...2015...} visits 0 winrate
 prior 10 lcb 0 order 29 pv C15
639.91 [85568] stdout| info move D4 visits 12 win{...2047...} visits 0 winrate
 prior 10 lcb 0 order 29 pv C15

**Comment by kaorahi** [comment] 2019-07-01 12:12
Very informative.

Lizgoban sent `komi 7.5`, `lz-analyze interval 1 minmoves 30`, `name`, `endstate_map`, ... to leelaz in rapid succession. But your leelaz ignored the third command `name` and the rest commands. Do you have any idea of a possible reason?

Anyway, we have to find a way to avoid this problem. Would you try these on "debug_issue29" branch? Please note that they are not solutions but just tests.

1. Does 857c0d1e work? [test A]
2. Does 0f767b5d work? [test D]
3. (if 2. is NO) Does 433f30aa work? (It will stop for a few seconds before working.) [test E]

**Comment by jun63cn** [comment] 2019-07-01 12:59
Good catch!  All three commits work well now. Thx  you anyway!

**Comment by kaorahi** [comment] 2019-07-02 12:28
I merged the above [test D] to the master branch and brushed it. Would you test 97b065d7?

BTW, I've never heard this problem from other users. What is special in your environment? Do you use some remote/cloud computer for leelaz?

**Comment by jun63cn** [comment] 2019-07-02 14:05
97b065d works well.   My system is Windows 7 Ultimate x64  core I7 6700  GPU gtx 1060.  I never used any remote/cloud computer for leelaz. Thx!

**Comment by kaorahi** [comment] 2019-07-03 11:56
thx for your help on debugging.

**Closed by kaorahi** 2019-07-03 11:56 UTC
